namespace BlackDesert.TradeMarket.Db.GameContext
{
	public partial class TblDeletedCharacterInformation
	{
		public DateTime? RegisterDate { get; set; }
		public bool? IsValid { get; set; }
		public long? UserNo { get; set; }
		public byte? SlotNo { get; set; }
		public long? CharacterNo { get; set; }
		public string? CharacterName { get; set; }
		public DateTime? DeletedDate { get; set; }
		public byte? ClassType { get; set; }
		public DateTime? LastLoginTime { get; set; }
		public DateTime? LastLogoutTime { get; set; }
		public long? TotalPlayTime { get; set; }
		public int? PcBasicCacheSeqNo { get; set; }
		public int? PcNonSavedCacheSeqNo { get; set; }
		public short? CurrentFieldNo { get; set; }
		public short? CurrentFieldIndex { get; set; }
		public long? CurrentPositionX { get; set; }
		public long? CurrentPositionY { get; set; }
		public long? CurrentPositionZ { get; set; }
		public short? ReturnFieldNo { get; set; }
		public short? ReturnFieldIndex { get; set; }
		public long? ReturnPositionX { get; set; }
		public long? ReturnPositionY { get; set; }
		public long? ReturnPositionZ { get; set; }
		public int? Level { get; set; }
		public long? Experience { get; set; }
		public int? SkillPointLevel { get; set; }
		public int? SkillPointExperience { get; set; }
		public int? RemainedSkillPoint { get; set; }
		public int? AquiredSkillPoint { get; set; }
		public int? ProductSkillPointExperience { get; set; }
		public int? RemainedProductSkillPoint { get; set; }
		public int? AquiredProductSkillPoint { get; set; }
		public int? Tendency { get; set; }
		public int? Hp { get; set; }
		public int? Mp { get; set; }
		public int? Sp { get; set; }
		public int? Wp { get; set; }
		public int? VariedMaxHp { get; set; }
		public int? VariedMaxMp { get; set; }
		public int? VariedDirectHit { get; set; }
		public int? VariedDirectDv { get; set; }
		public int? VariedDirectPv { get; set; }
		public int? VariedRangeHit { get; set; }
		public int? VariedRangeDv { get; set; }
		public int? VariedRangePv { get; set; }
		public int? VariedMagicalHit { get; set; }
		public int? VariedMagicalDv { get; set; }
		public int? VariedMagicalPv { get; set; }
		public int? RewardPoint { get; set; }
		public int? QuestLevelLog { get; set; }
		public byte? NewMail { get; set; }
		public byte? NewFriend { get; set; }
		public byte? NewRequestFriend { get; set; }
		public int? CreationIndex { get; set; }
		public byte? InventorySlotCount { get; set; }
		public int? ReservedLearningSkillKey { get; set; }
		public bool? IsRideTypeServant { get; set; }
		public long? RideVariousNo { get; set; }
		public byte? RideSeatIndex { get; set; }
		public bool? IsOnTypeServant { get; set; }
		public long? OnVariousNo { get; set; }
		public int? VariedWeight { get; set; }
		public int? TitleKey { get; set; }
		public int? KillRewardCount { get; set; }
		public int? EnchantFailCount { get; set; }
		public int? EnchantPcRoomCount { get; set; }
		public int? EnchantProtectBrokenCount { get; set; }
		public int? ArrivalRegionKey { get; set; }
		public DateTime? ArrivalTime { get; set; }
		public int? EnchantValuePackCount { get; set; }
		public int? RankPointPvp { get; set; }
		public int? AccumulatedKillCountByLocalWar { get; set; }
		public long? RestoreExperience { get; set; }
		public long? MurdererStateEndTime { get; set; }
		public int? LastBiddingItemKey { get; set; }
		public int? BiddingFailCount { get; set; }
		public int? SkillAwakeningCount { get; set; }
		public int? WeaponSkillAwakeningCount { get; set; }
		public bool? IsSpecialCharacter { get; set; }
		public byte? SeasonType { get; set; }
		public int? SuccessionSkillAwakeningCount { get; set; }
	}
}
